#!/bin/bash
#SBATCH -J myGPU     # job name
#SBATCH -o myGPU%j   # output and error file name (%j expands to job ID)
#SBATCH -N 2         # number of nodes
#SBATCH -n 4         # total number of cores
#SBATCH -p gtx       # queue (partition) -- normal, development, etc.
#SBATCH -t 00:01:00  # run time (hh:mm:ss) - 20 seconds
#SBATCH -A EE-382C-EE-361C-Mult
#SBATCH --mail-user=kayvan.mansoor@utexas.edu # where to email
#SBATCH --mail-type=begin		      # when to email (start)
#SBATCH --mail-type=end			      # when to email (end)
./funcTest
